routing_audits:
    resource: "@CiscoSystemsAuditBundle/Resources/config/routing/audits.yml"
    prefix:   /audits

routing_forms:
    resource: "@CiscoSystemsAuditBundle/Resources/config/routing/forms.yml"
    prefix:   /forms

routing_sections:
    resource: "@CiscoSystemsAuditBundle/Resources/config/routing/sections.yml"
    prefix:   /sections

routing_fields:
    resource: "@CiscoSystemsAuditBundle/Resources/config/routing/fields.yml"
    prefix:   /fields

# temp
cisco_audit_iconset:
    pattern: /iconset
    defaults: { _controller: CiscoSystemsAuditBundle:Audit:showIconSet }


