# audit path
wgaudit_add:
    pattern:  /audits/{id}/new
    defaults: {_controller: WGAuditBundle:Audit:add}  

wgaudit_view:
    pattern:  /audits/{id}
    defaults: {_controller: WGAuditBundle:Audit:view}
    
wgaudits:
    pattern:  /audits
    defaults: {_controller: WGAuditBundle:Audit:index}
    
# audit forms path  
wgauditform_edit:
    pattern:  /forms/{id}/edit
    defaults: {_controller: WGAuditBundle:AuditForm:edit}
   
wgauditform_remove:
    pattern:  /forms/{id}/remove
    defaults: {_controller: WGAuditBundle:AuditForm:remove}    

wgauditform_list:
    pattern:  /forms/list
    defaults: {_controller: WGAuditBundle:AuditForm:list}   

wgauditform_view:
    pattern:  /forms/{id}
    defaults: {_controller: WGAuditBundle:AuditForm:view}

wgauditform_add:
    pattern:  /forms/add
    defaults: {_controller: WGAuditBundle:AuditForm:edit} 

wgauditforms:
    pattern:  /forms
    defaults: {_controller: WGAuditBundle:AuditForm:index}    

# audit form sections path    
wgauditformsection_edit:
    pattern:  /sections/{id}/edit
    defaults: {_controller: WGAuditBundle:AuditFormSection:edit}
    
wgauditformsection_remove:
    pattern:  /sections/{id}/remove
    defaults: {_controller: WGAuditBundle:AuditFormSection:remove}    

wgauditformsection_view:
    pattern:  /sections/{id}
    defaults: {_controller: WGAuditBundle:AuditFormSection:view}
    
wgauditformsection_add:
    pattern:  /sections/add
    defaults: {_controller: WGAuditBundle:AuditFormSection:edit}   
    
wgauditformsections:
    pattern:  /sections
    defaults: {_controller: WGAuditBundle:AuditFormSection:index}

# audit form fields path
wgauditformfield_add:
    pattern:  /fields/add
    defaults: {_controller: WGAuditBundle:AuditFormField:edit}  

wgauditformfield_edit:
    pattern:  /fields/{id}/edit
    defaults: {_controller: WGAuditBundle:AuditFormField:edit}    

wgauditformfield_remove:
    pattern:  /fields/{id}/remove
    defaults: {_controller: WGAuditBundle:AuditFormField:remove} 
    
wgauditformfield_view:
    pattern:  /fields/{id}
    defaults: {_controller: WGAuditBundle:AuditFormField:view}
    
wgauditformfields:
    pattern:  /fields
    defaults: {_controller: WGAuditBundle:AuditFormField:index}


    
