# audit path
wgaudit_add:
    pattern:  /audits/{id}/new
    defaults: {_controller: WGAuditBundle:Audit:add}  

wgaudit:
    pattern:  /audits/{id}
    defaults: {_controller: WGAuditBundle:Audit:view}
    
wgaudits:
    pattern:  /audits
    defaults: {_controller: WGAuditBundle:Audit:index}
    
# audit forms path    
wgauditforms:
    pattern:  /forms
    defaults: {_controller: WGAuditBundle:AuditForm:index}    
    
wgauditform_list:
    pattern:  /forms/viewall
    defaults: {_controller: WGAuditBundle:AuditForm:list}
    
# audit form sections path    
wgauditformsection_edit:
    pattern:  /section/{id}/edit
    defaults: {_controller: WGAuditBundle:AuditFormSection:edit}
    
wgauditformsection_remove:
    pattern:  /section/{id}/remove
    defaults: {_controller: WGAuditBundle:AuditFormSection:remove}    

wgauditformsection_view:
    pattern:  /section/{id}
    defaults: {_controller: WGAuditBundle:AuditFormSection:view}
    
wgauditformsection_add:
    pattern:  /section
    defaults: {_controller: WGAuditBundle:AuditFormSection:edit}   
    
wgauditformsections:
    pattern:  /sections
    defaults: {_controller: WGAuditBundle:AuditFormSection:index}

# audit form fields path

wgauditformfield_edit:
    pattern:  /field/{id}/edit
    defaults: {_controller: WGAuditBundle:AuditFormField:edit}    

wgauditformfield_remove:
    pattern:  /field/{id}/remove
    defaults: {_controller: WGAuditBundle:AuditFormField:remove} 
    
wgauditformfield_view:
    pattern:  /field/{id}
    defaults: {_controller: WGAuditBundle:AuditFormField:view}
    
wgauditformfield_add:
    pattern:  /field
    defaults: {_controller: WGAuditBundle:AuditFormField:edit}    

wgauditformfields:
    pattern:  /fields
    defaults: {_controller: WGAuditBundle:AuditFormField:index}


    
