
auditformsections:
    pattern:  /sections
    defaults: {_controller: WGAuditBundle:AuditFormSection:index}

auditformfields:
    pattern:  /fields
    defaults: {_controller: WGAuditBundle:AuditFormField:index}
    
auditforms:
    pattern:  /forms
    defaults: {_controller: WGAuditBundle:AuditForm:index}