WGAuditBundle_form:
    resource: "@WGAuditBundle/Resources/config/routing/auditform.yml"
    prefix:   /forms

WGAuditBundle_section:
    resource: "@WGAuditBundle/Resources/config/routing/auditformfield.yml"
    prefix:   /sections

WGAuditBundle_field:
    resource: "@WGAuditBundle/Resources/config/routing/auditformsection.yml"
    prefix:   /fields

# audit path
wgaudit_add:
    pattern:  /audits/{id}/new
    defaults: { _controller: WGAuditBundle:Audit:add }
    requirements:
        id: \d+

wgaudit_view:
    pattern:  /audits/{id}
    defaults: { _controller: WGAuditBundle:Audit:view }
    requirements:
        id: \d+

wgaudits:
    pattern:  /audits
    defaults: { _controller: WGAuditBundle:Audit:index }

# temp
wgaudit_iconset:
    pattern: /iconset
    defaults: { _controller: WGAuditBundle:Audit:showIconSet }


