parameters:
    cisco.formtype.audit.class: CiscoSystems\AuditBundle\Form\Type\AuditType

services:
    cisco.formtype.audit:
        class: %cisco.formtype.audit.class%
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
          - { name: form.type, alias: audit }
