parameters:
    cisco.formtype.audit.class:           CiscoSystems\AuditBundle\Form\Type\AuditType
    cisco.twig.auditbundle_extension.class:    CiscoSystems\AuditBundle\Twig\Extension\AuditBundleExtension
    cisco.worker.audit_score.class:      CiscoSystems\AuditBundle\Worker\AuditScoring

services:
    cisco.formtype.audit:
        class: %cisco.formtype.audit.class%
        tags:
            - { name: form.type, alias: audit }

    cisco.twig.auditbundle_extension:
        class: %cisco.twig.auditbundle_extension.class%
        arguments:
            - '@cisco.worker.audit_score'
        tags:
            - { name: twig.extension }

    cisco.worker.audit_score:
        class:  %cisco.worker.audit_score.class%
