parameters:
    cisco.formtype.audit.class: CiscoSystems\AuditBundle\Form\Type\AuditType

services:
    cisco.formtype.audit:
        class: %cisco.formtype.audit.class%
        tags:
            - { name: form.type, alias: audit }
