cisco_audit_add:
    pattern:  /new/{form}
    defaults: { _controller: CiscoSystemsAuditBundle:Audit:add }
    requirements:
        id: \d+

cisco_audit_view:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:Audit:view }
    requirements:
        id: \d+

cisco_audits:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:Audit:index }
