cisco_auditformfield_add:
    pattern:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:edit }

cisco_auditformfield_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:edit }
    requirements:
        id: \d+

cisco_auditformfield_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:delete }
    requirements:
        id: \d+

cisco_auditformfield_calculate_score:
    pattern:  /calculate-score
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:calculateScore }
    requirements:
        _method:  POST
        _format:  JSON

cisco_auditformfield_view:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:view }
    requirements:
        id: \d+

cisco_auditformfield_load:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:load }
    requirements:
        id: \d+

cisco_auditformfields:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:index }
