cisco_auditfield_add:
    pattern:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:edit }

cisco_auditfield_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:edit }
    requirements:
        id: \d+

cisco_auditfield_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:delete }
    requirements:
        id: \d+

cisco_auditfield_calculate_score:
    pattern:  /calculate-score
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:calculateScore }
    requirements:
        _method:  POST
        _format:  JSON

cisco_auditfield_view:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:view }
    requirements:
        id: \d+

cisco_auditfield_load:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:load }
    requirements:
        id: \d+

cisco_auditfields:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:index }
