audit_form_add:
    path:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:Form:edit }

audit_form_list:
    path:  /list
    defaults: { _controller: CiscoSystemsAuditBundle:Form:list }

audit_form_edit:
    path:  /{form_id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:Form:edit }
    requirements:
        form_id: \d+

audit_form_delete:
    path:  /{form_id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:Form:delete }
    requirements:
        form_id: \d+

audit_form_add_section:
    path:  /{form_id}/section/{section_id}/add
    defaults: { _controller: CiscoSystemsAuditBundle:Form:add }
    requirements:
        form_id: \d+
        section_id: \d+

audit_form_new_section:
    path:  /{form_id}/sections/add
    defaults: { _controller: CiscoSystemsAuditBundle:Section:edit }
    requirements:
        form_id: \d+

audit_form_remove:
    path:  /{form_id}/section/{section_id}/remove
    defaults: { _controller: CiscoSystemsAuditBundle:Form:remove }
    requirements:
        form_id: \d+
        section_id: \d+

audit_form_view:
    path:  /{form_id}
    defaults: { _controller: CiscoSystemsAuditBundle:Form:view }
    requirements:
        form_id: \d+

audit_forms:
    path:  /
    defaults: { _controller: CiscoSystemsAuditBundle:Form:index }

