cisco_auditform_add:
    pattern:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:edit }

cisco_auditform_list:
    pattern:  /list
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:list }

cisco_auditform_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:edit }
    requirements:
        id: \d+

cisco_auditform_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:delete }
    requirements:
        id: \d+

cisco_auditform_add_section:
    pattern:  /{id}/section/{section_id}/add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:add }
    requirements:
        id: \d+
        section_id: \d+
        _method:  POST|GET
        _format:  JSON

cisco_auditform_new_section:
    pattern:  /{id}/sections/new
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:new }
    requirements:
        id: \d+

cisco_auditform_remove:
    pattern:  /{id}/section/{section_id}/remove
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:remove }
    requirements:
        _method:  POST|GET
        _format: JSON
        id: \d+
        section_id: \d+

cisco_auditform_view:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:view }
    requirements:
        id: \d+

cisco_auditforms:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:AuditForm:index }

