wgauditformsection_add:
    pattern:  /add
    defaults: { _controller: WGAuditBundle:AuditFormSection:edit }

wgauditformsection_edit:
    pattern:  /{id}/edit
    defaults: { _controller: WGAuditBundle:AuditFormSection:edit }
    requirements:
        id: \d+

wgauditformsection_delete:
    pattern:  /{id}/delete
    defaults: { _controller: WGAuditBundle:AuditFormSection:delete }
    requirements:
        id: \d+

wgauditformsection_add_field:
    pattern:  /{id}/field/{field_id}/add
    defaults: { _controller: WGAuditBundle:AuditFormSection:add }
    requirements:
        id: \d+
        field_id: \d+

wgauditformsection_remove:
    pattern:  /{id}/field/{field_id}/remove
    defaults: { _controller: WGAuditBundle:AuditFormSection:remove }
    requirements:
        _method:  POST|GET
        _format: json
        id: \d+
        field_id: \d+

wgauditformsection_view:
    pattern:  /{id}
    defaults: { _controller: WGAuditBundle:AuditFormSection:view }
    requirements:
        id: \d+

wgauditformsections:
    pattern:  /
    defaults: { _controller: WGAuditBundle:AuditFormSection:index }
