cisco_auditsection_add:
    pattern:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:edit }

cisco_auditsection_edit:
    pattern:  /{section_id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:edit }
    requirements:
        section_id: \d+

cisco_auditsection_delete:
    pattern:  /{section_id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:delete }
    requirements:
        section_id: \d+

cisco_auditsection_add_field:
    pattern:  /{section_id}/field/{field_id}/add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:add }
    requirements:
        section_id: \d+
        field_id: \d+

cisco_auditsection_new_field:
    pattern:  /{section_id}/add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormField:edit }
    requirements:
        section_id: \d+
        
cisco_auditsection_remove:
    pattern:  /{section_id}/field/{field_id}/remove
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:remove }
    requirements:
        section_id: \d+
        field_id: \d+

cisco_auditsection_view:
    pattern:  /{section_id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:view }
    requirements:
        section_id: \d+

cisco_auditsection_load:
    pattern:  /{section_id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:load }
    requirements:
        section_id: \d+

cisco_auditsections:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:index }