cisco_auditformsection_add:
    pattern:  /add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:edit }

cisco_auditformsection_edit:
    pattern:  /{id}/edit
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:edit }
    requirements:
        id: \d+

cisco_auditformsection_delete:
    pattern:  /{id}/delete
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:delete }
    requirements:
        id: \d+

cisco_auditformsection_add_field:
    pattern:  /{id}/field/{field_id}/add
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:add }
    requirements:
        _method:  POST|GET
        _format: JSON
        id: \d+
        field_id: \d+

cisco_auditformsection_remove:
    pattern:  /{id}/field/{field_id}/remove
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:remove }
    requirements:
        id: \d+
        field_id: \d+

cisco_auditformsection_view:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:view }
    requirements:
        id: \d+

cisco_auditformsection_load:
    pattern:  /{id}
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:load }
    requirements:
        id: \d+

cisco_auditformsections:
    pattern:  /
    defaults: { _controller: CiscoSystemsAuditBundle:AuditFormSection:index }
